Sio 6
SUMIO1/SUMIO pull request #4
Opened 2024-05-08 10:49 UTC by marcepanowyy

2024-05-08 12:43 UTC, Kacper0199 requested changes
Wszystko Ok. Dodałbym jednak sugestie, które napisałem wyżej, żeby spełnić kryteria akceptacyjne

2024-05-08 12:43 UTC, Kacper0199 commented on src/example_package/csv_reader/csv_reader.py
> +        if not all(col in df.columns for col in required_columns):
Fajnie zrobione

2024-05-08 12:43 UTC, Kacper0199 commented on src/example_package/csv_reader/csv_reader.py
> +required_columns = ['name', 'surname', 'age_category', 'weight', 'country', 'image_url']
- Tą listę przeniósłbym do osobnego pliku w tej samej ścieżce. Plik przechowywałby wtedy "stałe" oraz zdefiniowane przez nas ograniczenia i predefiniowane kategorie. Dodatkowo zamiast tworzyć kilka osobnych list sugerowałbym stworzenie słownika w tym osobnym pliku, o którym mówię. Przykład:

constraints = {
   "required_columns": ["name", "surname", ....],
   "age_categories": ["Men-U20", "Women-U17", "Men-Senior", ...], # Trzeba zastanowić się nad kilkoma sensownymi kategoriami
   "weight_categories": [...],
   "max_weight": 500,
   "min_weight": 40
}


- Sugerowałbym się internetem co do kategorii:
http://www.ifs-sumo.org/ifs-weight-class.html

- Zrobic prosty checker dla nazw krajów. Najlepiej załóżmy, że przyjmujemy pełne nazwy krajów po angielsku. Zrobiłbym to za pomocą biblio pycountry, linki:
https://stackoverflow.com/questions/41245330/check-if-a-country-entered-is-one-of-the-countries-of-the-world
https://medium.com/@richamonga86/do-you-want-to-check-if-country-name-coming-in-your-data-is-correct-or-not-5583cee1b960

- url będziemy weryfikować na etapie wyświetlania info o zawodnikach pozniej przy drabince turniejowej

2024-05-08 12:43 UTC, Kacper0199 commented on src/example_package/csv_reader/csv_reader.py
> +    try:
dodałbym jeszcze tutaj sprawdzanie: df.isnull().values.any() i owinąć w try. Przy samym ładowaniu danych chcemy sprawdzić czy wszystko gra, przynajmniej wg mnie

2024-05-08 15:50 UTC, marcepanowyy commented on src/example_package/csv_reader/csv_reader.py
> +required_columns = ['name', 'surname', 'age_category', 'weight', 'country', 'image_url']
done, dodałem age+weight

2024-05-08 15:51 UTC, marcepanowyy commented on src/example_package/csv_reader/csv_reader.py
> +required_columns = ['name', 'surname', 'age_category', 'weight', 'country', 'image_url']
ja wgl bym ten plik config przeniósł do roota

2024-05-08 15:51 UTC, marcepanowyy commented on src/example_package/csv_reader/csv_reader.py
> +    try:
dodałem walidatory

2024-05-09 08:51 UTC, Kacper0199 approved these changes
wszystko Ok

2024-05-09 17:18 UTC, Kacper0199 requested changes
Czekamy jeszcze na subtaski SIO-29, SIO-30, SIO-56, SIO-57

2024-05-09 17:28 UTC, closed without merging