[SIO-29] - Wczytanie i załadowanie zawartości CSV do aplikacji
SUMIO1/SUMIO pull request #6
Opened 2024-05-09 17:29 UTC by marcepanowyy

2024-05-09 17:35 UTC, Kacper0199 approved these changes
Wcześniej sprawdzone - jest OK

2024-05-09 18:47 UTC, Strattoss requested changes
Kosmetyczne sugestie

2024-05-09 18:47 UTC, Strattoss commented on src/example_package/csv_reader/csv_reader.py
> +        if weight < min_weight or weight > max_weight:
Można w sumie skorzystać z pythonowych udogodnień składni.
```suggestion
        if not min_weight <= weight <= max_weight:
```
Tylko trzeba jeszcze pomyśleć, czy zrobić nierówności ostre czy nieostre. Moja sugestia powinna być równoważna obecnemu kodowi.

2024-05-09 18:47 UTC, Strattoss commented on src/example_package/csv_reader/config.py
> +constraints = {
Nie zamierzamy modyfikować tego słownika w czasie działania aplikacji, prawda? Jeśli tak, to można to zaznaczyć
```suggestion
from typing import Final

CONSTRAINTS: Final[dict] = {
```

2024-05-10 09:08 UTC, Strattoss commented on src/example_package/csv_reader/config.py
> +constraints = {
Ok, cofam to. Bez typingu, niech na razie będzie dynamicznie. Wystarczy napisać capslockiem.

2024-05-10 09:34 UTC, Strattoss approved these changes

2024-05-10 09:39 UTC, merged